/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mechanicalregister;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author micae
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(0, 0, 0)); // Define o fundo como preto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotInserir = new javax.swing.JLabel();
        rotConsultar = new javax.swing.JLabel();
        rotApagar = new javax.swing.JLabel();
        btInserirCliente = new javax.swing.JButton();
        btInserirVeiculo = new javax.swing.JButton();
        btInserirServico = new javax.swing.JButton();
        btConsultarCliente = new javax.swing.JButton();
        btConsultarProduto = new javax.swing.JButton();
        btConsultarServico = new javax.swing.JButton();
        btApagarCliente = new javax.swing.JButton();
        btApagarVeiculo = new javax.swing.JButton();
        btApagarServico = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btConsultarServico1 = new javax.swing.JButton();
        btConsultarServico2 = new javax.swing.JButton();
        btConsultarServico3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        rotInserir.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        rotInserir.setForeground(new java.awt.Color(255, 255, 255));
        rotInserir.setText("INSERIR:");

        rotConsultar.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        rotConsultar.setForeground(new java.awt.Color(255, 255, 255));
        rotConsultar.setText("CONSULTAR:");

        rotApagar.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        rotApagar.setForeground(new java.awt.Color(255, 255, 255));
        rotApagar.setText("APAGAR:");

        btInserirCliente.setBackground(new java.awt.Color(93, 40, 221));
        btInserirCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btInserirCliente.setForeground(new java.awt.Color(255, 255, 255));
        btInserirCliente.setText("CLIENTE");
        btInserirCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btInserirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirClienteActionPerformed(evt);
            }
        });

        btInserirVeiculo.setBackground(new java.awt.Color(93, 40, 221));
        btInserirVeiculo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btInserirVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btInserirVeiculo.setText("PRODUTO");
        btInserirVeiculo.setPreferredSize(new java.awt.Dimension(100, 50));
        btInserirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirVeiculoActionPerformed(evt);
            }
        });

        btInserirServico.setBackground(new java.awt.Color(93, 40, 221));
        btInserirServico.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btInserirServico.setForeground(new java.awt.Color(255, 255, 255));
        btInserirServico.setText("SERVIÇO");
        btInserirServico.setPreferredSize(new java.awt.Dimension(100, 50));
        btInserirServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirServicoActionPerformed(evt);
            }
        });

        btConsultarCliente.setBackground(new java.awt.Color(93, 40, 221));
        btConsultarCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btConsultarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarCliente.setText("CLIENTE");
        btConsultarCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarClienteActionPerformed(evt);
            }
        });

        btConsultarProduto.setBackground(new java.awt.Color(93, 40, 221));
        btConsultarProduto.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btConsultarProduto.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarProduto.setText("PRODUTO");
        btConsultarProduto.setPreferredSize(new java.awt.Dimension(100, 50));
        btConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarProdutoActionPerformed(evt);
            }
        });

        btConsultarServico.setBackground(new java.awt.Color(93, 40, 221));
        btConsultarServico.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btConsultarServico.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarServico.setText("SERVIÇO");
        btConsultarServico.setPreferredSize(new java.awt.Dimension(100, 50));
        btConsultarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarServicoActionPerformed(evt);
            }
        });

        btApagarCliente.setBackground(new java.awt.Color(93, 40, 221));
        btApagarCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btApagarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btApagarCliente.setText("CLIENTE");
        btApagarCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btApagarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarClienteActionPerformed(evt);
            }
        });

        btApagarVeiculo.setBackground(new java.awt.Color(93, 40, 221));
        btApagarVeiculo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btApagarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btApagarVeiculo.setText("PRODUTO");
        btApagarVeiculo.setPreferredSize(new java.awt.Dimension(100, 50));
        btApagarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarVeiculoActionPerformed(evt);
            }
        });

        btApagarServico.setBackground(new java.awt.Color(93, 40, 221));
        btApagarServico.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btApagarServico.setForeground(new java.awt.Color(255, 255, 255));
        btApagarServico.setText("SERVIÇO");
        btApagarServico.setPreferredSize(new java.awt.Dimension(100, 50));
        btApagarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarServicoActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(93, 40, 221));
        btSair.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btSair.setForeground(new java.awt.Color(255, 255, 255));
        btSair.setText("SAIR");
        btSair.setPreferredSize(new java.awt.Dimension(100, 50));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btConsultarServico1.setBackground(new java.awt.Color(93, 40, 221));
        btConsultarServico1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btConsultarServico1.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarServico1.setText("VEICULO");
        btConsultarServico1.setPreferredSize(new java.awt.Dimension(100, 50));
        btConsultarServico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarServico1ActionPerformed(evt);
            }
        });

        btConsultarServico2.setBackground(new java.awt.Color(93, 40, 221));
        btConsultarServico2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btConsultarServico2.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarServico2.setText("CLIENTES COM CARRO");
        btConsultarServico2.setPreferredSize(new java.awt.Dimension(100, 50));
        btConsultarServico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarServico2ActionPerformed(evt);
            }
        });

        btConsultarServico3.setBackground(new java.awt.Color(93, 40, 221));
        btConsultarServico3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btConsultarServico3.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarServico3.setText("CLIENTES QUE COMPRARAM ALGUM PRODUTO");
        btConsultarServico3.setPreferredSize(new java.awt.Dimension(100, 50));
        btConsultarServico3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarServico3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(rotInserir))
                                    .addComponent(btInserirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btInserirVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btInserirServico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btConsultarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rotConsultar)
                                    .addComponent(btConsultarServico1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(rotApagar))
                                    .addComponent(btApagarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btApagarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btApagarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(btConsultarServico2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btConsultarServico3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotApagar)
                        .addGap(31, 31, 31)
                        .addComponent(btApagarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btApagarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotInserir)
                        .addGap(31, 31, 31)
                        .addComponent(btInserirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btInserirVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotConsultar)
                        .addGap(31, 31, 31)
                        .addComponent(btConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btApagarServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInserirServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultarServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btConsultarServico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btConsultarServico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btConsultarServico3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirClienteActionPerformed
        InserirCliente inserirCliente = new InserirCliente();
        inserirCliente.setVisible(true);
    }//GEN-LAST:event_btInserirClienteActionPerformed

    private void btInserirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirVeiculoActionPerformed
        InserirProduto inserirVeiculo = new InserirProduto();
        inserirVeiculo.setVisible(true);
    }//GEN-LAST:event_btInserirVeiculoActionPerformed

    private void btInserirServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirServicoActionPerformed
        InserirServico inserirServico = new InserirServico();
        inserirServico.setVisible(true);
    }//GEN-LAST:event_btInserirServicoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void btConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarClienteActionPerformed
        ConsultarCliente consultarCliente = new ConsultarCliente();
        consultarCliente.setVisible(true);
    }//GEN-LAST:event_btConsultarClienteActionPerformed

    private void btConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarProdutoActionPerformed
        ConsultarProduto consultarProduto = new ConsultarProduto();
        consultarProduto.setVisible(true);
    }//GEN-LAST:event_btConsultarProdutoActionPerformed

    private void btConsultarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarServicoActionPerformed
        ConsultarServico consultarServico = new ConsultarServico();
        consultarServico.setVisible(true);
    }//GEN-LAST:event_btConsultarServicoActionPerformed

    private void btApagarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarServicoActionPerformed
        ApagarServico apagarServico = new ApagarServico();
        apagarServico.setVisible(true);
    }//GEN-LAST:event_btApagarServicoActionPerformed

    private void btApagarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarVeiculoActionPerformed
        ApagarProduto apagarVeiculo = new ApagarProduto();
        apagarVeiculo.setVisible(true);
    }//GEN-LAST:event_btApagarVeiculoActionPerformed

    private void btApagarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarClienteActionPerformed
        ApagarCliente apagarCliente = new ApagarCliente();
        apagarCliente.setVisible(true);
    }//GEN-LAST:event_btApagarClienteActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btConsultarServico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarServico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarServico1ActionPerformed

    private void btConsultarServico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarServico2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarServico2ActionPerformed

    private void btConsultarServico3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarServico3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarServico3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApagarCliente;
    private javax.swing.JButton btApagarServico;
    private javax.swing.JButton btApagarVeiculo;
    private javax.swing.JButton btConsultarCliente;
    private javax.swing.JButton btConsultarProduto;
    private javax.swing.JButton btConsultarServico;
    private javax.swing.JButton btConsultarServico1;
    private javax.swing.JButton btConsultarServico2;
    private javax.swing.JButton btConsultarServico3;
    private javax.swing.JButton btInserirCliente;
    private javax.swing.JButton btInserirServico;
    private javax.swing.JButton btInserirVeiculo;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel rotApagar;
    private javax.swing.JLabel rotConsultar;
    private javax.swing.JLabel rotInserir;
    // End of variables declaration//GEN-END:variables
}
