/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mechanicalregister;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author micae
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotInserir = new javax.swing.JLabel();
        rotConsultar = new javax.swing.JLabel();
        rotApagar = new javax.swing.JLabel();
        btInserirCliente = new javax.swing.JButton();
        btInserirVeiculo = new javax.swing.JButton();
        btInserirServico = new javax.swing.JButton();
        btConsultarCliente = new javax.swing.JButton();
        btConsultarVeiculo = new javax.swing.JButton();
        btConsultarServico = new javax.swing.JButton();
        btApagarCliente = new javax.swing.JButton();
        btApagarVeiculo = new javax.swing.JButton();
        btApagarServico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rotInserir.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        rotInserir.setForeground(new java.awt.Color(255, 255, 255));
        rotInserir.setText("INSERIR:");
        getContentPane().add(rotInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        rotConsultar.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        rotConsultar.setForeground(new java.awt.Color(255, 255, 255));
        rotConsultar.setText("CONSULTAR:");
        getContentPane().add(rotConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        rotApagar.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        rotApagar.setForeground(new java.awt.Color(255, 255, 255));
        rotApagar.setText("APAGAR:");
        getContentPane().add(rotApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, -1, -1));

        btInserirCliente.setBackground(new java.awt.Color(93, 40, 221));
        btInserirCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btInserirCliente.setForeground(new java.awt.Color(255, 255, 255));
        btInserirCliente.setText("CLIENTE");
        btInserirCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btInserirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btInserirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 149, -1));

        btInserirVeiculo.setBackground(new java.awt.Color(93, 40, 221));
        btInserirVeiculo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btInserirVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btInserirVeiculo.setText("VEICULO");
        btInserirVeiculo.setPreferredSize(new java.awt.Dimension(100, 50));
        btInserirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirVeiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btInserirVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 149, -1));

        btInserirServico.setBackground(new java.awt.Color(93, 40, 221));
        btInserirServico.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btInserirServico.setForeground(new java.awt.Color(255, 255, 255));
        btInserirServico.setText("SERVIÇO");
        btInserirServico.setPreferredSize(new java.awt.Dimension(100, 50));
        btInserirServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirServicoActionPerformed(evt);
            }
        });
        getContentPane().add(btInserirServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 149, 50));

        btConsultarCliente.setBackground(new java.awt.Color(93, 40, 221));
        btConsultarCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btConsultarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarCliente.setText("CLIENTE");
        btConsultarCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 149, -1));

        btConsultarVeiculo.setBackground(new java.awt.Color(93, 40, 221));
        btConsultarVeiculo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btConsultarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarVeiculo.setText("VEICULO");
        btConsultarVeiculo.setPreferredSize(new java.awt.Dimension(100, 50));
        btConsultarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarVeiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 149, -1));

        btConsultarServico.setBackground(new java.awt.Color(93, 40, 221));
        btConsultarServico.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btConsultarServico.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarServico.setText("SERVIÇO");
        btConsultarServico.setPreferredSize(new java.awt.Dimension(100, 50));
        btConsultarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarServicoActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 149, -1));

        btApagarCliente.setBackground(new java.awt.Color(93, 40, 221));
        btApagarCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btApagarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btApagarCliente.setText("CLIENTE");
        btApagarCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btApagarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btApagarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 149, -1));

        btApagarVeiculo.setBackground(new java.awt.Color(93, 40, 221));
        btApagarVeiculo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btApagarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btApagarVeiculo.setText("VEICULO");
        btApagarVeiculo.setPreferredSize(new java.awt.Dimension(100, 50));
        btApagarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarVeiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btApagarVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 149, -1));

        btApagarServico.setBackground(new java.awt.Color(93, 40, 221));
        btApagarServico.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btApagarServico.setForeground(new java.awt.Color(255, 255, 255));
        btApagarServico.setText("SERVIÇO");
        btApagarServico.setPreferredSize(new java.awt.Dimension(100, 50));
        btApagarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarServicoActionPerformed(evt);
            }
        });
        getContentPane().add(btApagarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, 149, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo .png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirClienteActionPerformed
        try (Connection conexao = new Conexao().getConnection()) {
                String sql = "insert into carro_cliente(nome_cliente, marca, modelo) values('Bre Brena', 'Renault', 'K+');";
                PreparedStatement statement = conexao.prepareStatement(sql);
                statement.execute();
                conexao.close();
            } catch (SQLException ex) {
                
            }
    }//GEN-LAST:event_btInserirClienteActionPerformed

    private void btInserirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInserirVeiculoActionPerformed

    private void btInserirServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInserirServicoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void btConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarClienteActionPerformed

    private void btConsultarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarVeiculoActionPerformed

    private void btConsultarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarServicoActionPerformed

    private void btApagarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btApagarServicoActionPerformed

    private void btApagarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btApagarVeiculoActionPerformed

    private void btApagarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btApagarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApagarCliente;
    private javax.swing.JButton btApagarServico;
    private javax.swing.JButton btApagarVeiculo;
    private javax.swing.JButton btConsultarCliente;
    private javax.swing.JButton btConsultarServico;
    private javax.swing.JButton btConsultarVeiculo;
    private javax.swing.JButton btInserirCliente;
    private javax.swing.JButton btInserirServico;
    private javax.swing.JButton btInserirVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rotApagar;
    private javax.swing.JLabel rotConsultar;
    private javax.swing.JLabel rotInserir;
    // End of variables declaration//GEN-END:variables
}
